### ISSUE TITLE
Project Doesn't Build -- FlickrFetchr Classes Missing

### ISSUE THREAD

**Issue by LoganWright** [IntrepidPursuits/code-review-benc#1]
The project doesn't build because these classes are missing.   You added them after I asked, but they are not linked with the project.

Referenced Commit: 
AlgorithmicAscension/FlickFetcher@f678295

**Comment by AlgorithmicAscension** [comment]
FlickrFetcher Classes added
Referenced Commit:
f67829507c7158a14e15f2a902949d21f18b5c2c

**Comment by LoganWright** [comment]
@AlgorithmicAscension - In the future, please add a link to the commit / project that has been fixed.  I'll close this one, but just a note going forward.
